### ISSUE TITLE
缺少文件#include "create_and_write_txt.c"

### ISSUE THREAD

**Issue by jvruoben** [euaurora/HappyShares-CNST-HEU#14]
网络空间信息安全里面引的文件#include "create_and_write_txt.c"是学长自己编写的吗？还留有文件记录吗？

**Comment by DMCXE** [comment]
感谢反馈！已将缺失文件create_and_write_txt.c补充回目录中

**Comment by DMCXE** [comment]
> 网络空间信息安全里面引的文件#include "create_and_write_txt.c"是学长自己编写的吗？还留有文件记录吗？

感谢反馈！已将文件create_and_write_txt.c补充至目录

**Comment by jvruoben** [comment]
太感谢学长了！！
